server:
  port: 81
  shutdown: graceful # 优雅关机

spring:
  profiles:
    active: dev,druid,express
  thymeleaf:
    cache: false
    suffix: .html
    check-template-location: false
  servlet:
    multipart:
      enabled: true
      location: ${wayn.uploadDir}
      file-size-threshold: 5MB
      max-file-size: 200MB
      max-request-size: 200MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌秘钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 120

# 日志配置
logging:
  level:
    com.wayn: debug
    org.springframework: info
    com.baomidou: info

# mybatis plus 配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  # 搜索指定包别名
  typeAliasesPackage: com.wayn.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml

# wayn配置
wayn:
  name: wayn
  version: 1.1.0
  email: 166738430@qq.com
  uploadDir: /opt/wayn/upload # linux下文件上传目录
  #  uploadDir: D:/wayn/upload # windows下文件上传目录
  adminUrl: http://mall.wayn.ltd:81
  mobileUrl: http://mall.wayn.ltd:82
  ssh-proxy: # ssh端口代理设置，eg:通过ssh连接公网服务器，在通过端口转发访问内网服务器的服务
    enabled: false                      # 是否启用
    host:                               # 服务器host
    port:                               # 服务器port
    username:                           # 服务器登陆用户名称
    password:                           # 服务器登陆用户密码
    localPort:                          # 代理本地端口
    remoteHost:                         # 需要代理的服务host
    remotePort:                         # 需要代理的服务port



#滑块验证码配置
aj:
  captcha:
    aes-status: true
    cache-type: redis
    font-size: 25
    font-style: 1
    history-data-clear-enable: false
    interference-options: 0
    jigsaw: classpath:images/capthcha
    req-check-minute-limit: 60
    req-frequency-limit-enable: true
    req-get-lock-limit: 2
    req-get-lock-seconds: 360
    req-get-minute-limit: 30
    req-verify-minute-limit: 60
    slip-offset: 5
    type: default
    water-mark: wayn
