server:
  port: 85

spring:
  redis:
    host: huawei.wayn.ltd
    port: 1688
    timeout: 5000
    password: admin@@123456
    database: 2
    expire: 400
  # 配置rabbitMq 服务器
  rabbitmq:
    host: huawei.wayn.ltd
    port: 5672
    username: guest
    password: guest
    # 消息确认配置项
    # 确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    # 确认消息已发送到队列(Queue)
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100

# 日志配置
logging:
  level:
    com.wayn: debug
    org.springframework: info
