server:
  port: 85
  shutdown: graceful # 优雅关机
spring:
  application:
    name: waynboot-message-consumer
  redis:
    host: 122.112.205.44
    port: 1688
    timeout: 5000
    password: admin@@123456
    database: 2
    expire: 400
  # 配置rabbitMq 服务器
  rabbitmq:
    host: 122.112.205.44
    port: 5672
    username: guest
    password: guest
    # 消息确认配置项
    # 确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    # 确认消息已发送到队列(Queue)
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100
  boot:
    admin:
      client:
        url: http://localhost:89


# 日志配置
logging:
  level:
    com.wayn: debug
    org.springframework: info
  file:
    name: ${LOG_PATH_PREFIX:E:/home}/${spring.application.name}/info.log

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    logfile:
      external-file: ${logging.file.name}
    health:
      show-details: always
