# 数据源配置
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    # 主库数据源
    master:
      url: jdbc:mysql://127.0.0.1:3306/wayn_shop?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
    # 从库数据源
    slave:
      # 从数据源开关/默认关闭
      enabled: false
      url:
      username:
      password:

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 2
    timeout: 5000
    expire: 400
    lettuce:
      shutdown-timeout: 100ms
  #    cluster:
  #      nodes:
  #        - 127.0.0.1:1681
  #        - 127.0.0.1:1682
  #        - 127.0.0.1:1683
  #        - 127.0.0.1:1684
  #        - 127.0.0.1:1685
  #        - 127.0.0.1:1686
  #配置rabbitMq 服务器
  rabbitmq:
    host: wayn.ltd
    port: 5672
    username: guest
    password: guest
    # 消息确认配置项
    # 确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    # 确认消息已发送到队列(Queue)
    publisher-returns: true

es:
  host: huawei.wayn.ltd
  port: 9200
  scheme: http
  shards: 3
  replicas: 2

# alipay 需要自行申请支付宝的沙箱账号、申请appID，并依次配置AppID、密钥、公钥，否则无法发起支付宝支付。
alipay:
  app-id:
  rsa-private-key:
  alipay-public_key:
  gateway: https://openapi.alipaydev.com/gateway.do
  charset: UTF-8
  format: json
  #  log_path: /opt/newbeeplus/log
  log_path: D://newbeemallplus//log
  signtype: RSA2
